GET http://localhost:3001/api/users
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJhbmFsZG8iLCJwYXNzd29yZCI6IiQyYiQxMCRMR2NPemZuR3RCZDcxU3NtNm5xM1dlN1lVdi9acTU3NHBHYm05bVRsdE8uLmJZNjBYMXI2UyIsImlhdCI6MTY1Mjk3ODM0N30.j07a_oQa4B9A3XspnNNHLqysCklUdtkYOoOiwPKMU7E

###
GET http://localhost:3001/api/users/ranaldo
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50aW4iLCJpYXQiOjE2NTMwNjU2MzF9.DYYsYWwwvbeQyrhaijn-gzKXEC5-jD_FHhPRAxO65Vk

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ubuntinin",
  "password": "123123"
}

###
DELETE http://localhost:3001/api/users/1

###
PUT http://localhost:3001/api/users/4
Content-Type: application/json

{
  "username": "Lowrins",
  "password": "laurita"
}