GET http://localhost:3001/api/users

###
GET http://localhost:3001/api/users/ubuntininin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50aW5pbmluIiwiaWF0IjoxNjUzMDcyMzQ0fQ.K4S8IeJJ-gUtI08AJHFUk6opQ6F8ta1SQJLa9L7aEHk

###
POST http://localhost:3001/api/users
Content-Type: application/json

{
  "username": "ubuntininin",
  "password": "123123"
}

###
DELETE http://localhost:3001/api/users/ubuntininin
Authorization: bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InVidW50aW5pbmluIiwiaWF0IjoxNjUzMDcyMzQ0fQ.K4S8IeJJ-gUtI08AJHFUk6opQ6F8ta1SQJLa9L7aEHk

###
PUT http://localhost:3001/api/users/4
Content-Type: application/json

{
  "username": "Lowrins",
  "password": "laurita"
}